version: '3.7'

services:
  app: 
    build : 
      context: ./app
    volumes: 
      - ./app:/srv
    command: yarn watch

  web:
    build : 
      context: ./web
    volumes:
      - ./app/dist:/public/
    depends_on:
      - app
    ports:
      - "${WEB_PORT}:80"

