version: '3.7'

services:
  app: 
    build : .
    volumes: 
      - ./:/srv
    command: yarn start
    environment:
      - "PORT=$PORT"
    ports:
      - "$PORT:$PORT"
  storybook:
    build : .
    volumes:
      - ./:/srv
    command: yarn storybook
    ports:
      - "${STORYBOOK_PORT}:9001"
