version: '3.7'

services:
  app: 
    build : .
    volumes: 
      - ./:/srv
    command: yarn start
    environment:
      - "PORT=$PORT"
    ports:
      - "$PORT:$PORT"
  storybook:
    build : .
    volumes:
      - ./:/srv
    environment:
      - "STORYBOOK_PORT=$STORYBOOK_PORT"
    command: yarn storybook -p $STORYBOOK_PORT
    ports:
      - "$STORYBOOK_PORT:$STORYBOOK_PORT"
